stages:
    - test
    - examples

test_docker:
    stage: test
    image: ubuntu:rolling
    tags: 
            - docker.meteo.physik.lmu.de
    before_script:
        - apt update
        - export DEBIAN_FRONTEND=noninteractive
        - apt install -yq git python3 python3-pip python3-venv
    script: ./run_tests.sh
